spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunzhanyi_1.5.0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
logging:
  file:
    name: logs\admin.log

swagger:
  description: 云沾衣后台管理系统统一管理网站的一切
  title: 云沾衣后台管理系统API
  version: 1.5.0
  base-package: net.yunzhanyi.admin.controller
  contact:
    email: 977961764@qq.com
    name: bestct
security:
  ignore:
    whites:
      - /login
      - /logout
      - /doc.html
      - /webjars/**
      - /v3/**
      - /captcha/**

aj:
  captcha:
    jigsaw: classpath:images/jigsaw
    cache-type: local
    type: blockpuzzle
    water-mark: 云沾衣
