server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  #数据库的信息配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yzy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: net.yunzhanyi.admin.mapper

#日志的配置
logging:
  level:
    net:
      yunzhanyi:
        admin:
          mapper: debug
