spring:
  profiles:
    active: @profiles.active@
  #允许循环依赖
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  application:
    name: yunzhanyi
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  file:
    name: logs\client.log

swagger:
  description: 云沾衣门户网站Api
  title: 云沾衣门户网站API
  version: 1.1.0
  base-package: net.yunzhanyi.client.controller
  email: 977961764@qq.com
  name: bestct
  url: https://github.com/bestct

springdoc:
  api-docs:
    enabled: true

security:
  token:
    redis-key-prefix: "yunzhanyi:client"
    time-unit: days
    expire-time: 30
