server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunzhanyi_1.5.0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
logging:
  file:
    name: logs\client.log

swagger:
  description: 云沾衣门户网站Api
  title: 云沾衣门户网站API
  version: 1.5.0
  base-package: net.yunzhanyi.client.controller
  contact:
    email: 977961764@qq.com
    name: bestct

security:
  token:
    redis-key-prefix: "net:yunzhanyi:client"
    time-unit: minutes
    expire-time: 1
